version: '3'

services:
  ros2:
    build: .
    ipc: host
    tty: true
    privileged: true
    image: humble-desktop
    container_name: ros2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - DISPLAY=novnc:0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1700
      - DISPLAY_HEIGHT=1728
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: